{% set name = "splito" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/splito-{{ version }}.tar.gz
  sha256: a54ea50eb70a1ad4853c97430e78c388d18c1080def416f77f246d5ac27e9d83

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - tqdm
    - loguru
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - matplotlib-base
    - seaborn
    - jenkspy
    - datamol >=0.12.5

test:
  imports:
    - splito
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Machine Learning dataset splitting for life sciences.
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/datamol-io/splito

extra:
  recipe-maintainers:
    - cwognum
