{% set name = "splito" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/splito-{{ version }}.tar.gz
  sha256: 2df5f031f3b987e66a5326a9b50d2fbb59ba25010a3f5f9090717130436a0ff7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - tqdm
    - loguru
    - pydantic
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - matplotlib-base
    - seaborn
    - jenkspy
    - datamol

test:
  imports:
    - splito
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Machine Learning dataset splitting for life sciences.
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/datamol-io/splito

extra:
  recipe-maintainers:
    - hadim
